name: tests

on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  test:
    name: Install package and run pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pip and other dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools pytest
          python setup.py install
      - name: Run pytest
        run: |
          python -m pytest
